# Generated by Django 4.2.7 on 2023-11-21 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("context", models.TextField()),
                ("conclusion", models.TextField()),
                ("seo_description", models.TextField()),
                ("seo_keywords", models.TextField()),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("context", models.TextField()),
                ("related_image", models.ImageField(upload_to="media/")),
                ("code", models.TextField()),
                ("tail_text", models.TextField()),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="main.blog",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="main.category"
            ),
        ),
    ]
