# Generated by Django 4.2.7 on 2023-11-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_category_slug_alter_thread_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="thread_link",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
