# Generated by Django 4.2.7 on 2023-11-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_thread_thread_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default="2021-01-27"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="views",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="main.category",
            ),
        ),
    ]
