# Generated by Django 4.2.7 on 2023-11-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_blog_created_blog_views_alter_blog_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="category",
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ManyToManyField(related_name="blogs", to="main.category"),
        ),
    ]
