# Generated by Django 4.2.7 on 2023-11-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_blog_category_blog_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="views",
            field=models.PositiveBigIntegerField(default=121),
        ),
    ]
