# Generated by Django 4.2.7 on 2023-11-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_blog_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="rm_counter",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
