# Generated by Django 4.2.7 on 2023-11-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_blog_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ("-created",),
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="accent",
            field=models.CharField(blank=True, default="#04baf6", max_length=20),
        ),
        migrations.AlterField(
            model_name="blog",
            name="allow_comments",
            field=models.CharField(
                choices=[("allow", "allow"), ("disallow", "disallow")],
                default="disallow",
                max_length=30,
            ),
        ),
    ]
