# Generated by Django 4.2 on 2023-11-29 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0011_alter_blog_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.ManyToManyField(
                related_name="author", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
