# Generated by Django 4.2 on 2023-11-29 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0012_remove_blog_author_blog_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
        migrations.AddField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
