# Generated by Django 4.2.7 on 2023-11-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_remove_blog_author_blog_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="related_image",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
