# Generated by Django 4.2.7 on 2023-11-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_thread_related_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="link_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
