# Generated by Django 4.2.7 on 2023-11-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_thread_link_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
