# Generated by Django 4.2.7 on 2023-11-30 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_blog_featured_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="rm_counter",
        ),
    ]
